// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<void> initCore({required String tempDir}) =>
    RustLib.instance.api.crateApiSimpleInitCore(tempDir: tempDir);

Future<String> startServer({required int port, required String name}) =>
    RustLib.instance.api.crateApiSimpleStartServer(port: port, name: name);

Future<void> stopServer() => RustLib.instance.api.crateApiSimpleStopServer();

Future<String> stageFile({required String path}) =>
    RustLib.instance.api.crateApiSimpleStageFile(path: path);

Future<String> stageText({required String text}) =>
    RustLib.instance.api.crateApiSimpleStageText(text: text);

Future<void> unstageItem({required String id}) =>
    RustLib.instance.api.crateApiSimpleUnstageItem(id: id);

Future<List<StagedItem>> getStagedItems() =>
    RustLib.instance.api.crateApiSimpleGetStagedItems();

Future<List<StagedItem>> getReceivedItems() =>
    RustLib.instance.api.crateApiSimpleGetReceivedItems();

Future<void> removeReceivedItem({required String id}) =>
    RustLib.instance.api.crateApiSimpleRemoveReceivedItem(id: id);

Future<void> cleanCache() => RustLib.instance.api.crateApiSimpleCleanCache();

Stream<DiscoveredService> startDiscovery() =>
    RustLib.instance.api.crateApiSimpleStartDiscovery();

Future<void> stopDiscovery() =>
    RustLib.instance.api.crateApiSimpleStopDiscovery();

Stream<UploadRequest> startUploadListener() =>
    RustLib.instance.api.crateApiSimpleStartUploadListener();

Future<void> resolveUpload({required String id, required bool accepted}) =>
    RustLib.instance.api.crateApiSimpleResolveUpload(
      id: id,
      accepted: accepted,
    );

Stream<double> downloadFile({required String url, required String savePath}) =>
    RustLib.instance.api.crateApiSimpleDownloadFile(
      url: url,
      savePath: savePath,
    );

class DiscoveredService {
  final String id;
  final String nodeName;
  final String ip;
  final int port;

  const DiscoveredService({
    required this.id,
    required this.nodeName,
    required this.ip,
    required this.port,
  });

  @override
  int get hashCode =>
      id.hashCode ^ nodeName.hashCode ^ ip.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredService &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nodeName == other.nodeName &&
          ip == other.ip &&
          port == other.port;
}

class StagedItem {
  final String id;
  final String name;
  final StagedItemType itemType;
  final String? path;
  final String? text;
  final BigInt size;

  const StagedItem({
    required this.id,
    required this.name,
    required this.itemType,
    this.path,
    this.text,
    required this.size,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      itemType.hashCode ^
      path.hashCode ^
      text.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StagedItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          itemType == other.itemType &&
          path == other.path &&
          text == other.text &&
          size == other.size;
}

enum StagedItemType { file, text }

class UploadRequest {
  final String id;
  final String name;
  final BigInt size;

  const UploadRequest({
    required this.id,
    required this.name,
    required this.size,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadRequest &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          size == other.size;
}
